### ISSUE TITLE
tests: move specs from `tests/unit/**/*` into packages

### ISSUE THREAD

**Issue by kellymears** [roots/bud#1625]
This is too big a process to hinge on a single PR. We'll take it on piecemeal until `tests/unit` is empty. Then we'll close this issue.

This PR lays the groundwork: https://github.com/roots/bud/pull/1623. 

Tests should:

- be alongside their corresponding module
- import code directly from that module
- be named roughly in accordance with the pattern established in #1623.
  - `@roots/bud-api/src/methods/assets/index.ts` becomes:
    - `@roots/bud-api/src/methods/assets/assets.method.ts`
    - `@roots/bud-api/src/methods/assets/assets.unit.test.ts`
    
## @roots/bud-api

- [ ] `@roots/bud-api/methods/alias`
- [x] `@roots/bud-api/methods/assets` (#1623)
- [x] `@roots/bud-api/methods/bundle` (#1623)
- [x] `@roots/bud-api/methods/config` (#1623)
- [x] `@roots/bud-api/methods/define` (#1623)
- [x] `@roots/bud-api/methods/devtool` (#1715)
- [x] `@roots/bud-api/methods/entry` (#1715)
- [x] `@roots/bud-api/methods/experiments` (#1715)
- [x] `@roots/bud-api/methods/externals` (#1715)
- [x] `@roots/bud-api/methods/hash` (#1734)
- [x] `@roots/bud-api/methods/minimize` (#1734)
- [x] `@roots/bud-api/methods/persist` (#1734)
- [x] `@roots/bud-api/methods/provide` (#1734)
- [x] `@roots/bud-api/methods/proxy` (#1734)
- [ ] `@roots/bud-api/methods/runtime`
- [x] `@roots/bud-api/methods/serve` (#1623)
- [ ] `@roots/bud-api/methods/splitChunks`
- [ ] `@roots/bud-api/methods/template`
- [ ] `@roots/bud-api/methods/use`
- [ ] `@roots/bud-api/methods/watch`
- [x] `@roots/bud-api/service` (#1623)

## @roots/bud-build
- [x] `@roots/bud-build/config` (#1754)

## @roots/bud-cache

- [x] `@roots/bud-cache/service` (#1754)
- [x] `@roots/bud-cache/invalidate-cache-extension` (#1754)

## @roots/bud-compiler

- [x] `@roots/bud-compiler` (#1734)

## @roots/bud-framework

- [x] `@roots/bud-framework/lifecycle/bootstrap` (#1715)
- [x] `@roots/bud-framework/methods/setPath` (#1715)

## @roots/bud-hooks

- [x] `@roots/bud-hooks/service` (#1754)

## @roots/bud-server

- [x] all existing tests (#1606)

## @roots/bud

- [x] `@roots/bud/factory` (#1754)
- [x] `@roots/bud/extensions/*` (#1754)

## @roots/filesystem
- [x] `@roots/filesystem` (#1754)
- [x] `@roots/filesystem/s3` (#1754)

## extensions

- [x] `@roots/bud-preset-wordpress/*` (#1727)
- [x] `@roots/bud-sass` (#1734)
- [x] `@roots/bud-sass/resolve-url` (#1734)
- [x] `@roots/bud-react` (#1754)
- [x] `@roots/bud-react/babel-refresh` (#1754)
- [x] `@roots/bud-react/typescript-refresh` (#1754)
- [x] `@roots/bud-react/swc-refresh` (#1754)
- [x] `@roots/bud-react/react-refresh` (#1754)
- [x] `@roots/bud-esbuild` (#1754)
- [x] `@roots/bud-eslint` (#1754)
- [x] `@roots/bud-solid` (#1754)
- [x] `@roots/bud-swc` (#1754)
- [x] `@roots/bud-stylelint` (#1754)
- [x] `@roots/bud-terser` (#1754)
- [x] `@roots/bud-vue` (#1754)
- [x] `@roots/bud-wordpress-dependencies` (#1754)
- [x] `@roots/bud-wordpress-externals` (#1754)
- [x] `@roots/bud-wordpress-manifests` (#1754)
- [x] `@roots/bud-emotion` (#1754)
- [x] `@roots/bud-compress` (#1754)
- [x] `@roots/bud-babel` (#1754)
