### ISSUE TITLE
Deprecate internal usage of @roots/bud-typings

### ISSUE THREAD

**Issue by kellymears** [roots/bud#48]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

`@roots/bud-typings` helped get this project off the ground but it is no longer wanted/needed. Instead, it should export aggregate type definitions from the rest of the packages for consumption by third parties, etc.

## Motivation

- Encourages decoupling of packages
- Related: makes `@roots/bud-framework` more fault tolerant and easier to extend / provide alternate implementations for.
- Lessens developer friction (switching contexts to `@roots/bud-typings` when working on another package is bothersome). 

## Notes

- `@roots/bud-compiler` needed refactoring for Webpack 5. This was handled alongside that work (#43)

## Todo

- [ ] @roots/bud-api
- [x] @roots/bud-build (https://github.com/roots/bud/commit/7208d51cfa5adfc603e86d451a330e85ac8a8444)
- [ ] @roots/bud-cli
- [x] @roots/bud-compiler (#43) 
- [x] @roots/bud-dashboard (#47)
- [ ] @roots/bud-extensions
- [ ] @roots/bud-framework
- [ ] @roots/bud-hooks
- [ ] @roots/bud-server
